from __future__ import annotations

import logging
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Literal

from models.schemas import PageResult, ParseRequest, ParseResponse
from utils.file_handler import get_file_path

logger = logging.getLogger(__name__)

ROOT_DIR = Path(__file__).resolve().parent.parent.parent

PARSER_FILES = {
    "pdfplumber": "pdfplumber.py",
    "docling": "docling.py",
    "doctr": "doctr.py",
    "camelot": "Camelot.py",
    "pdfminer": "pdfminer_runner.py",
    "marker": "marker.py",
    "unstructured": "Unstructured.py",
    "mineru": "MinorU.py",
    "grobif": "grobif.py",
    "layoutparser": "layoutparser.py",
    "paddleocr": "paddle.py",
    "easyocr": "easyocr.py",
    "tesseract": "tesseract.py",
    "rapidocr": "rapidocr.py",
    "suryaocr": "suryaocr.py",
    "tabula": "tabula.py",
    "liteparse": "liteparse.py",
    "llmsherpha": "llmsherpha.py",
}

PAGE_HEADER_RE = re.compile(r"^\s*---\s*Page\s+(\d+)\s*/\s*\d+\s*---\s*$", re.IGNORECASE)

MineruProfile = Literal["fast", "quality", "balanced"]


def _mineru_profile_env(profile: MineruProfile | None) -> dict[str, str]:
    """Env overrides for MinorU.py / mineru CLI (same semantics as CLI presets)."""
    if profile is None:
        return {}
    if profile == "fast":
        return {
            "MINERU_BACKEND": "pipeline",
            "MINERU_METHOD": "txt",
            "MINERU_FORMULA": "0",
            "MINERU_TABLE": "0",
            "MINERU_LANG": "en",
        }
    if profile == "quality":
        return {
            "MINERU_BACKEND": "hybrid-auto-engine",
            "MINERU_METHOD": "auto",
            "MINERU_FORMULA": "1",
            "MINERU_TABLE": "1",
            "MINERU_LANG": "ch",
        }
    # balanced
    return {
        "MINERU_BACKEND": "pipeline",
        "MINERU_METHOD": "auto",
        "MINERU_FORMULA": "0",
        "MINERU_TABLE": "1",
        "MINERU_LANG": "en",
    }


def _discover_extracted_outputs(
    work_dir: Path, parser_name: str, pdf_path: Path, started_at: float
) -> list[Path]:
    """Find extracted output written either in temp work dir or project root.

    Many parser scripts currently write relative to their own file location
    instead of the subprocess cwd. Keep supporting both locations.
    """
    candidates: list[Path] = []

    # Preferred location: per-request temp work directory.
    candidates.extend(work_dir.glob("*_extracted/extracted.txt"))
    candidates.extend(work_dir.glob("*_extracted/extracted.md"))
    for d in work_dir.iterdir():
        if not d.is_dir():
            continue
        txt_file = d / "extracted.txt"
        md_file = d / "extracted.md"
        if txt_file.exists():
            candidates.append(txt_file)
        elif md_file.exists():
            candidates.append(md_file)

    # Fallback location: parser scripts that write under project root.
    pdf_stem = pdf_path.stem
    for d in ROOT_DIR.glob(f"{pdf_stem}_extracted*"):
        if not d.is_dir():
            continue
        txt_file = d / "extracted.txt"
        md_file = d / "extracted.md"
        if txt_file.exists():
            candidates.append(txt_file)
        if md_file.exists():
            candidates.append(md_file)

    # Keep files likely generated by this run.
    fresh: list[Path] = []
    for p in candidates:
        try:
            if p.stat().st_mtime >= (started_at - 2):
                fresh.append(p)
        except OSError:
            continue

    # Prefer parser-specific directory names, then newest file.
    parser_token = parser_name.lower()
    deduped = list(dict.fromkeys(fresh))
    deduped.sort(
        key=lambda p: (
            parser_token not in p.parent.name.lower(),
            -p.stat().st_mtime,
        )
    )
    return deduped


def _run_parser_script(
    parser_name: str,
    pdf_path: Path,
    work_dir: Path,
    mineru_profile: MineruProfile | None = None,
) -> list[PageResult]:
    script_name = PARSER_FILES.get(parser_name.lower())
    if not script_name:
        return [PageResult(page=1, text=f"[ERROR] Unknown parser: {parser_name}")]

    script_path = ROOT_DIR / script_name
    if not script_path.exists():
        return [
            PageResult(page=1, text=f"[ERROR] Parser script not found: {script_name}")
        ]

    logger.info(f"Running parser {parser_name} on {pdf_path.name}")

    run_env = os.environ.copy()
    timeout_sec = 300
    if parser_name.lower() == "mineru":
        timeout_sec = 900
        if mineru_profile:
            overrides = _mineru_profile_env(mineru_profile)
            run_env.update(overrides)
            logger.info(
                "MinerU profile=%s overrides: %s",
                mineru_profile,
                overrides,
            )

    try:
        work_pdf = work_dir / pdf_path.name
        shutil.copy2(pdf_path, work_pdf)
        # Several legacy scripts look for Holiday 2026.pdf in cwd; keep a second copy when needed.
        legacy_name = work_dir / "Holiday 2026.pdf"
        if work_pdf.resolve() != legacy_name.resolve():
            shutil.copy2(work_pdf, legacy_name)

        if parser_name.lower() == "mineru":
            # MinorU reads MINERU_SOURCE or cwd; pin path so temp-dir runs are unambiguous.
            run_env["MINERU_SOURCE"] = str(work_pdf.resolve())
        if parser_name.lower() == "paddleocr":
            run_env["PADDLEOCR_SOURCE"] = str(work_pdf.resolve())
        if parser_name.lower() == "llmsherpha":
            run_env["LLMSHERPA_SOURCE"] = str(work_pdf.resolve())

        started_at = time.time()
        result = subprocess.run(
            [sys.executable, str(script_path)],
            cwd=str(work_dir),
            capture_output=True,
            text=True,
            timeout=timeout_sec,
            env=run_env,
        )

        if result.returncode != 0:
            logger.error(f"Parser {parser_name} failed: {result.stderr[:500]}")
            return [PageResult(page=1, text=f"[ERROR] {result.stderr[:1000]}")]

        extracted_files = _discover_extracted_outputs(
            work_dir=work_dir,
            parser_name=parser_name,
            pdf_path=pdf_path,
            started_at=started_at,
        )

        if not extracted_files:
            return [
                PageResult(
                    page=1, text=f"[WARNING] No output file generated by {parser_name}"
                )
            ]

        content = extracted_files[0].read_text(encoding="utf-8", errors="replace")

        # Prefer page-wise chunks when parser output contains explicit page headers.
        pages: list[PageResult] = []
        current_page: int | None = None
        buffer: list[str] = []

        for line in content.splitlines():
            m = PAGE_HEADER_RE.match(line)
            if m:
                if current_page is not None:
                    pages.append(
                        PageResult(page=current_page, text="\n".join(buffer).strip())
                    )
                current_page = int(m.group(1))
                buffer = []
                continue
            buffer.append(line)

        if current_page is not None:
            pages.append(PageResult(page=current_page, text="\n".join(buffer).strip()))
        else:
            # Fallback for parsers that don't emit page headers.
            pages = [PageResult(page=1, text=content.strip())]

        logger.info(f"Parser {parser_name} completed with {len(pages)} page entries")
        return pages

    except subprocess.TimeoutExpired:
        logger.error(f"Parser {parser_name} timed out")
        return [
            PageResult(
                page=1,
                text=f"[ERROR] Parser timed out after {timeout_sec // 60} minutes",
            )
        ]
    except Exception as e:
        logger.error(f"Parser {parser_name} error: {e}")
        return [PageResult(page=1, text=f"[ERROR] {str(e)}")]


async def parse_pdf(request: ParseRequest) -> ParseResponse:
    logger.info(f"Parsing file_id={request.file_id} with parsers={request.parsers}")

    pdf_path = get_file_path(request.file_id)
    if not pdf_path or not pdf_path.exists():
        raise ValueError(f"File not found for file_id: {request.file_id}")

    parser_results: dict[str, list[PageResult]] = {}

    with tempfile.TemporaryDirectory() as work_dir:
        work_path = Path(work_dir)

        for parser_name in request.parsers:
            logger.info(f"Running parser: {parser_name}")
            try:
                profile = (
                    request.mineru_profile
                    if parser_name.lower() == "mineru"
                    else None
                )
                results = _run_parser_script(
                    parser_name, pdf_path, work_path, mineru_profile=profile
                )
                parser_results[parser_name] = results
            except Exception as e:
                logger.error(f"Error running parser {parser_name}: {e}")
                parser_results[parser_name] = [
                    PageResult(page=1, text=f"[ERROR] {str(e)}")
                ]

    return ParseResponse(parsers=parser_results)


def available_parsers() -> list[str]:
    available = []
    for name, script in PARSER_FILES.items():
        if (ROOT_DIR / script).exists():
            available.append(name)
    return available
